"use strict";
exports.__esModule = true;
exports.ListaObras = void 0;
var Obra_1 = require("./Obra");
var ListaObras = /** @class */ (function () {
    function ListaObras() {
        this.obras = [];
    }
    ListaObras.prototype.adicionarObra = function (obra) {
        this.obras.push(obra);
    };
    ListaObras.prototype.acharObra = function (autor) {
        var obras = [];
        for (var i = 0; i < this.obras.length; i++) {
            if (autor == this.obras[i].getAutor()) {
                obras.push(this.obras[i]);
            }
        }
        return obras;
    };
    return ListaObras;
}());
exports.ListaObras = ListaObras;
var listaobras = new ListaObras();
var formacaorural = new Obra_1.Obra();
formacaorural.setAutor("SantaGuerra");
formacaorural.setTitulo("formacaorural");
formacaorural.setTituloPublico("Formação Rural");
listaobras.adicionarObra(formacaorural);
var omenordosmeusirmaos = new Obra_1.Obra();
omenordosmeusirmaos.setAutor("SantaGuerra");
omenordosmeusirmaos.setTitulo("omenordosmeusirmaos");
omenordosmeusirmaos.setTituloPublico("O Menor dos Meus Irmãos");
listaobras.adicionarObra(omenordosmeusirmaos);
var aabelinhasonhadora = new Obra_1.Obra();
aabelinhasonhadora.setAutor("NatiCortez");
aabelinhasonhadora.setTitulo("aabelinhasonhadora");
aabelinhasonhadora.setTituloPublico("A Abelinha Sonhadora");
listaobras.adicionarObra(aabelinhasonhadora);
var aguerradosplanetas = new Obra_1.Obra();
aguerradosplanetas.setAutor("NatiCortez");
aguerradosplanetas.setTitulo("aguerradosplanetas");
aguerradosplanetas.setTituloPublico("A Guerra dos Planetas");
listaobras.adicionarObra(aguerradosplanetas);
var ivoneteI = new Obra_1.Obra();
ivoneteI.setAutor("ivonetealbano");
ivoneteI.setTitulo("ivoneteI");
ivoneteI.setTituloPublico("Recortes I");
listaobras.adicionarObra(ivoneteI);
var ivoneteII = new Obra_1.Obra();
ivoneteII.setAutor("ivonetealbano");
ivoneteII.setTitulo("ivoneteII");
ivoneteII.setTituloPublico("Recortes II");
listaobras.adicionarObra(ivoneteII);
var ivoneteIII = new Obra_1.Obra();
ivoneteIII.setAutor("ivonetealbano");
ivoneteIII.setTitulo("ivoneteIII");
ivoneteIII.setTituloPublico("Recortes III");
listaobras.adicionarObra(ivoneteIII);
var ivoneteIV = new Obra_1.Obra();
ivoneteIV.setAutor("ivonetealbano");
ivoneteIV.setTitulo("ivoneteIV");
ivoneteIV.setTituloPublico("Recortes IV");
listaobras.adicionarObra(ivoneteIV);
var aprovidencia = new Obra_1.Obra();
aprovidencia.setAutor("ManuelSWanderley");
aprovidencia.setTitulo("aprovidencia");
aprovidencia.setTituloPublico("A Providência");
listaobras.adicionarObra(aprovidencia);
var astresdatas = new Obra_1.Obra();
astresdatas.setAutor("ManuelSWanderley");
astresdatas.setTitulo("astresdatas");
astresdatas.setTituloPublico("As Três Datas");
listaobras.adicionarObra(astresdatas);
var oanjodameianoite = new Obra_1.Obra();
oanjodameianoite.setAutor("ManuelSWanderley");
oanjodameianoite.setTitulo("oanjodameianoite");
oanjodameianoite.setTituloPublico("O Anjo da Meia Noite");
listaobras.adicionarObra(oanjodameianoite);
var brasileiroseportugueses = new Obra_1.Obra();
brasileiroseportugueses.setAutor("ManuelSWanderley");
brasileiroseportugueses.setTitulo("brasileiroseportugueses");
brasileiroseportugueses.setTituloPublico("Brasileiros e Portugueses");
listaobras.adicionarObra(brasileiroseportugueses);
var osanjosdoclaustro = new Obra_1.Obra();
osanjosdoclaustro.setAutor("ManuelSWanderley");
osanjosdoclaustro.setTitulo("ivoneteIV");
osanjosdoclaustro.setTituloPublico("Os Anjos do Claustro");
listaobras.adicionarObra(osanjosdoclaustro);
var avemaria = new Obra_1.Obra();
avemaria.setAutor("PoncianoBarbosa");
avemaria.setTitulo("avemaria");
avemaria.setTituloPublico("Ave-Maria");
listaobras.adicionarObra(avemaria);
var cabecadomundo = new Obra_1.Obra();
cabecadomundo.setAutor("MeiraPires");
cabecadomundo.setTitulo("cabecadomundo");
cabecadomundo.setTituloPublico("Cabeça do Mundo");
listaobras.adicionarObra(cabecadomundo);
var umrestodehomem = new Obra_1.Obra();
umrestodehomem.setAutor("MeiraPires");
umrestodehomem.setTitulo("umrestodehomem");
umrestodehomem.setTituloPublico("Um Resto de Homem");
listaobras.adicionarObra(umrestodehomem);
var dialogodasestrelas = new Obra_1.Obra();
dialogodasestrelas.setAutor("NatiCortez");
dialogodasestrelas.setTitulo("dialogodasestrelas");
dialogodasestrelas.setTituloPublico("Diálogo das Estrelas");
listaobras.adicionarObra(dialogodasestrelas);
var onatalnoespacosideral = new Obra_1.Obra();
onatalnoespacosideral.setAutor("NatiCortez");
onatalnoespacosideral.setTitulo("onatalnoespacosideral");
onatalnoespacosideral.setTituloPublico("O Natal no Espaço Sideral");
listaobras.adicionarObra(onatalnoespacosideral);
var pelasgrades = new Obra_1.Obra();
pelasgrades.setAutor("JorgeFernandes");
pelasgrades.setTitulo("pelasgrades");
pelasgrades.setTituloPublico("Pelas Grades");
listaobras.adicionarObra(pelasgrades);
var umjardimchamadogetsemani = new Obra_1.Obra();
umjardimchamadogetsemani.setAutor("NewtonNavarro");
umjardimchamadogetsemani.setTitulo("umjardimchamadogetsemani");
umjardimchamadogetsemani.setTituloPublico("Um Jardim Chamado Getsêmani");
listaobras.adicionarObra(umjardimchamadogetsemani);
var EntrevistaOthon = new Obra_1.Obra();
EntrevistaOthon.setAutor("soniaothon");
EntrevistaOthon.setTitulo("EntrevistaOthon");
EntrevistaOthon.setTituloPublico("Entrevista na Integra");
listaobras.adicionarObra(EntrevistaOthon);
var EntrevistaRacine = new Obra_1.Obra();
EntrevistaRacine.setAutor("racinesantos");
EntrevistaRacine.setTitulo("EntrevistaRacine");
EntrevistaRacine.setTituloPublico("Entrevista na Integra");
listaobras.adicionarObra(EntrevistaRacine);
var EntrevistaIvonete = new Obra_1.Obra();
EntrevistaIvonete.setAutor("ivonetealbano");
EntrevistaIvonete.setTitulo("EntrevistaIvonete");
EntrevistaIvonete.setTituloPublico("Entrevista na Integra");
listaobras.adicionarObra(EntrevistaIvonete);
exports["default"] = listaobras;
